"""add server keypair to configuration

Revision ID: 0741bc76e748
Revises: 647a4418cc8c
Create Date: 2026-03-30 15:37:19.276524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0741bc76e748'
down_revision: Union[str, None] = '647a4418cc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configurations', sa.Column('server_private_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('configurations', sa.Column('server_public_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configurations', 'server_public_key')
    op.drop_column('configurations', 'server_private_key')
    # ### end Alembic commands ###
