[Interface]
PrivateKey = SALYR6RYKISfffOs7+PeQkiI7M5r73qwXYn4fo5Bjl4=

[Peer]
PublicKey = HdbPtoka8YH5EO0AE/c7qgpn+C+KJ3jb4PeKGwn38QU=
PresharedKey = NhqmMbL8ou6QfBREN8VmS/FX4aaYKwX+yvOESwVetTg=
Endpoint = wiregui:51820
AllowedIPs = 10.3.2.0/24
PersistentKeepalive = 5
