[Interface]
PrivateKey = EIvEgJvaZYF9g4iIyYaevV3GaEKoB4AXa6Z1M1b5qXQ=

[Peer]
PublicKey = HdbPtoka8YH5EO0AE/c7qgpn+C+KJ3jb4PeKGwn38QU=
PresharedKey = 0QBrDLFpiqXZWYMeQ1uXm5pujSKrwmqx5VC2D0ETTAo=
Endpoint = wiregui:51820
AllowedIPs = 10.3.2.0/24
PersistentKeepalive = 5
